### ISSUE TITLE
Cannot find module 'socket.io-client' error when updating from version 3.0.2 to 3.1.0 

### ISSUE THREAD

**Issue by Shadowsm29** [koltyakov/sp-rest-proxy#130]
Hi,

I've been using this package a lot lately and it really makes my life much easier. So first of all, thank you for making and maintaining it.

However when I updated the package from version 3.0.2 to 3.1.0, I get the following error upon running the script:

```
PS C:\temp\Repositories\P02467-ibss-training-portal-shp-vue> npm run proxy

> sp-proxy-test@0.1.0 proxy C:\temp\Repositories\P02467-ibss-training-portal-shp-vue
> node ./server.js

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'socket.io-client'
Require stack:
- C:\temp\Repositories\P02467-ibss-training-portal-shp-vue\node_modules\sp-rest-proxy\dist\gateway\client.js
- C:\temp\Repositories\P02467-ibss-training-portal-shp-vue\node_modules\sp-rest-proxy\dist\core\RestProxy.js
- C:\temp\Repositories\P02467-ibss-training-portal-shp-vue\node_modules\sp-rest-proxy\dist\index.js        
- C:\temp\Repositories\P02467-ibss-training-portal-shp-vue\server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\temp\Repositories\P02467-ibss-training-portal-shp-vue\node_modules\sp-rest-proxy\dist\gateway\client.js:51:26)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\temp\\Repositories\\P02467-ibss-training-portal-shp-vue\\node_modules\\sp-rest-proxy\\dist\\gateway\\client.js',
    'C:\\temp\\Repositories\\P02467-ibss-training-portal-shp-vue\\node_modules\\sp-rest-proxy\\dist\\core\\RestProxy.js',
    'C:\\temp\\Repositories\\P02467-ibss-training-portal-shp-vue\\node_modules\\sp-rest-proxy\\dist\\index.js',
    'C:\\temp\\Repositories\\P02467-ibss-training-portal-shp-vue\\server.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sp-proxy-test@0.1.0 proxy: `node ./server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sp-proxy-test@0.1.0 proxy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mg92qw\AppData\Roaming\npm-cache\_logs\2021-10-08T07_07_12_612Z-debug.log
```

My server.js file looks this, nothing special:

```
const RestProxy = require("sp-rest-proxy");

const settings = {
  configPath: "./config/private.json", // Location for SharePoint instance mapping and credentials
  port: 8080, // Local server port
  staticRoot: "./node_modules/sp-rest-proxy/static", // Root folder for static content
};

const restProxy = new RestProxy(settings);
restProxy.serve();
```

First I tried to update all packages with npm update command, then I reverted and tried to update only this one and this seems to cause the issue. This is not a breaking issue for us, I think we will continue to use the older version for now, but I wanted o report it, in case anyone else encounters it.

If my node or npm versions are required for debugging:

```
PS C:\temp\Repositories\P02467-ibss-training-portal-shp-vue> node -v
v14.15.1
PS C:\temp\Repositories\P02467-ibss-training-portal-shp-vue> npm -v
6.14.8
```

Thanks in advance for the support.

**Comment by koltyakov** [comment]
Thank you @Shadowsm29!

Could you please take a look if 3.1.1 works for you. If it doesn't work please try removing node_modules/, package-lock.json and reinstalling dependencies.
